# Generated by Django 3.2.6 on 2021-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('MW', 'Mens Wear'), ('WW', 'Womens Wear'), ('F', 'Food'), ('H', 'Households'), ('HW', 'HandWash'), ('S', 'Sanitizer')], max_length=2),
        ),
    ]
