# Generated by Django 3.2.6 on 2021-10-08 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_rename_ordered_data_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='wish_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
